# version: "3.8"

services:
  db:
    image: postgres:17-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}"]
      timeout: 20s
      retries: 10

  web:
    container_name: petproject101-web
    build: ./app
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    depends_on:
      - db

  script:
    container_name: petproject101-script
    build: ./script
    env_file:
      - .env
    volumes:
      - ./script:/app
    depends_on:
      - db
    command: ["python", "python_crawler.py"]

volumes:
  pgdata:
