name: Build & Push to ECR, then Deploy to EC2

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-southeast-1                  
  ECR_REPOSITORY_APP: petproject101-web          
  ECR_REPOSITORY_SCRIPT: petproject101-script   
  ECR_REGISTRY_URI: 157018355309.dkr.ecr.ap-southeast-1.amazonaws.com 

jobs:
  
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    
    - name: Build & Push App Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest 
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_APP:$IMAGE_TAG -f app/Dockerfile ./app
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_APP:$IMAGE_TAG

    
    - name: Build & Push Script Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_SCRIPT:$IMAGE_TAG -f script/Dockerfile ./script
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_SCRIPT:$IMAGE_TAG

  
  deploy-to-ec2:
    needs: build-and-push 
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        envs: AWS_REGION, ECR_REGISTRY_URI
        script: |
       
          
          cd PetProject101

          git fetch origin

          git reset --hard origin/main
          
          git pull origin main
          
          aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin $ECR_REGISTRY_URI
          
          sudo docker-compose pull

          sudo docker-compose up -d db

          sleep 30

          sudo docker-compose up -d web script 
          
          sudo docker image prune -f